name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.12'

    steps:
    - name: Clone repo
      uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.7.3"
        python-version: ${{ matrix.python-version }}

    - name: Create the virtual environment
      run: uv sync --all-groups --all-extras

    - name: Linting check
      run: uv run ruff check

    - name: Formatting check
      run: uv run ruff format --check

    - name: Type checking
      run: uv run pyright

    - name: Unit tests
      run: uv run pytest -Werror
